### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [Azzazzin14/prj-rev-bwfs-dasmoto#2]
https://github.com/Azzazzin14/prj-rev-bwfs-dasmoto/blob/master/DasmotoArtsandCrafts/index.html#L11-L30

Make sure to comment the main parts of your HTML in future projects. This becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/29745153-bada22ee-8a81-11e7-8f01-14893518ea0d.png">

**Comment by Azzazzin14** [comment]
Thanks for the advice, I just did not see a reason to make comments on code this straight forward. But I certainly understand why they are needed and how they can be so very helpful.... especially when I have to QA new branches for site updates at my job :)
